//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace C1Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C1Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   対象ソースファイル数が100を超えましたが続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_CONFIRM_MANY_SOURCE_FILE {
            get {
                return ResourceManager.GetString("MSGBOX_CONFIRM_MANY_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示している設定を破棄してよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_CONFIRM_REMOVE_FORM_CONFIG {
            get {
                return ResourceManager.GetString("MSGBOX_CONFIRM_REMOVE_FORM_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリッドの設定を破棄してよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_CONFIRM_REMOVE_GRID_CONFIG {
            get {
                return ResourceManager.GetString("MSGBOX_CONFIRM_REMOVE_GRID_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ソースファイルの設定を破棄してよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_CONFIRM_REMOVE_SOURCE_FILE_CONFIG {
            get {
                return ResourceManager.GetString("MSGBOX_CONFIRM_REMOVE_SOURCE_FILE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トレース追加を中止しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_CONFIRM_STOP_ADD_TRACE {
            get {
                return ResourceManager.GetString("MSGBOX_CONFIRM_STOP_ADD_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PowerShellスクリプトの実行に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_FAILED_RUN_POWERSHELL_SCRIPT {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_FAILED_RUN_POWERSHELL_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_LINE_1 {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_LINE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_LINE_2 {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_LINE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ソースファイルが選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_NOT_SELECT_SOURCE {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_NOT_SELECT_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルを指定していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_NOT_SPECIFIED_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_NOT_SPECIFIED_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張子を指定していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_NOT_SPECIFIED_EXTENSION {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_NOT_SPECIFIED_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対応していない拡張子です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_ERROR_NOT_SUPPORT_EXTENSION {
            get {
                return ResourceManager.GetString("MSGBOX_ERROR_NOT_SUPPORT_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トレース追加を終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_INFO_ADD_TRACE {
            get {
                return ResourceManager.GetString("MSGBOX_INFO_ADD_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルから読み込みました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_INFO_READ_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MSGBOX_INFO_READ_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル探索を終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_INFO_SEARCH_FILE {
            get {
                return ResourceManager.GetString("MSGBOX_INFO_SEARCH_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルへ書き込みました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBOX_INFO_WRITE_CONFIG_FILE {
            get {
                return ResourceManager.GetString("MSGBOX_INFO_WRITE_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   c1tester_add_trace.ps1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string POWERSHELL_SCRIPT {
            get {
                return ResourceManager.GetString("POWERSHELL_SCRIPT", resourceCulture);
            }
        }
    }
}
